version: '3'

services:

  customer1-producer:
    image: trexinc/customer-producer:1.0
    environment:
      TOPIC: customer1/outbound/corona
      PULSAR: $PULSAR
    networks:
      - local-pulsar-net

  customer2-producer:
    image: trexinc/customer-producer:1.0
    environment:
      TOPIC: customer2/outbound/corona
      PULSAR: $PULSAR
    networks:
      - local-pulsar-net

networks:
  local-pulsar-net:
    external:
      name: $PULSAR_NETWORK
